name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize, closed]

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './tinybird'
    services:
      tinybird:
        image: tinybirdco/tinybird-local:beta
        ports:
          - 7181:7181
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Need to fetch at least 2 commits to get the previous SHA
      - name: Install Tinybird CLI
        run: curl -LsSf https://api.tinybird.co/static/install.sh | sh
      - name: Build project
        run: tb build
      - name: Test project
        run: tb test run
      - name: Create preview workspace
        run: tb --cloud workspace create tb_${{ github.sha }} --user_token $TB_USER_TOKEN
      - name: Use new workspace
        run: tb --cloud workspace use tb_${{ github.sha }}
      - name: Deploy resources
        run: tb --cloud deploy
    env:
      TB_USER_TOKEN: ${{ secrets.TB_USER_TOKEN }}
      TB_HOST: ${{ secrets.TB_HOST }}

  cleanup:
    needs: ci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './tinybird'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get previous commit SHA
        id: get-prev-sha
        run: echo "sha=$(git rev-parse HEAD^)" >> $GITHUB_OUTPUT
      - name: Install Tinybird CLI
        run: curl -LsSf https://api.tinybird.co/static/install.sh | sh
      - name: Remove previous preview workspace
        run: tb --cloud workspace delete tb_${{ steps.get-prev-sha.outputs.sha }} --yes --user_token $TB_USER_TOKEN
    env:
      TB_TOKEN: ${{ secrets.TB_TOKEN }}
      TB_USER_TOKEN: ${{ secrets.TB_USER_TOKEN }}
      TB_HOST: ${{ secrets.TB_HOST }}
