
name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize, closed]

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './tinybird'
    services:
      tinybird:
        image: tinybirdco/tinybird-local:beta
        ports:
          - 7181:7181
    steps:
      - uses: actions/checkout@v3
      - name: Install Tinybird CLI
        run: curl -LsSf https://api.tinybird.co/static/install.sh | sh
      - name: Build project
        run: tb build
      - name: Test project
        run: tb test run
      - name: Create preview workspace
        run: tb --cloud workspace create ${{ github.sha }} --user_token $TB_USER_TOKEN
      - name: Deploy resources
        run: tb --cloud deploy
      - name: send mock data to preview workspace
        run: tb --cloud datasource append analytics_events fixtures/analytics_events.njson
    env:
      TB_TOKEN: ${{ secrets.TB_TOKEN }}
      TB_USER_TOKEN: ${{ secrets.TB_USER_TOKEN }}
      TB_HOST: ${{ secrets.TB_HOST }}
