name: Tinybird - CI Workflow

on:
  pull_request:
    branches:
      - main
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize, closed]

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  ci:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './tinybird'
    services:
      tinybird:
        image: tinybirdco/tinybird-local:beta
        ports:
          - 7181:7181
    steps:
      - uses: actions/checkout@v3
      - name: Install Tinybird CLI
        run: curl -LsSf https://api.tinybird.co/static/install.sh | sh
      - name: Build project
        run: tb build
      - name: Test project
        run: tb test run
      - name: Create preview workspace
        run: tb --cloud workspace create tb_${{ github.sha }} --user_token $TB_USER_TOKEN
      - name: Use new workspace
        run: tb --cloud workspace use tb_${{ github.sha }}
      - name: Deploy resources
        run: TB_TOKEN="" tb --cloud deploy
    env:
      TB_TOKEN: ${{ secrets.TB_TOKEN }}
      TB_USER_TOKEN: ${{ secrets.TB_USER_TOKEN }}
      TB_HOST: ${{ secrets.TB_HOST }}

  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './tinybird'
    steps:
      - name: Install Tinybird CLI
        run: curl -LsSf https://api.tinybird.co/static/install.sh | sh
      - name: Remove PR workspace
        run: tb --cloud workspace delete tb_${{ github.sha }} --yes --user_token $TB_USER_TOKEN
    env:
      TB_TOKEN: ${{ secrets.TB_TOKEN }}
      TB_USER_TOKEN: ${{ secrets.TB_USER_TOKEN }}
      TB_HOST: ${{ secrets.TB_HOST }}